---
name: Release

on:
  push:
    branches:
      - master
      - next
      - next-major
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x"

jobs:
  release:
    uses: EricCrosson/typescript-action/.github/workflows/release.yml@v1
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
